
#Define a custom Docker image to be used in workspaces
image: gitpod/workspace-node:latest

# List the start up tasks. Learn more https://www.gitpod.io/docs/config-start-tasks/
tasks:
  - init: echo 'init script' # runs during prebuild => is niet nodig
    command: docker compose up -d

# List the ports to expose. Learn more https://www.gitpod.io/docs/config-ports/
ports:
  - name: Website
    port: 80
    onOpen: open-browser
  - name: db
    port: 3306
    onOpen: ignore

# Define a list of extensions which should be installed for users of this workspace
vscode:
  extensions:
    - dbaeumer.vscode-eslint
    - ms-azuretools.vscode-docker
