version: '3.9'

services:
  front-end:
    image: nginx:1.22
    volumes:
      - ./frontend/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./frontend:/var/www/static/:ro
    ports:
      - 80:80
    depends_on:
      - todo-api-service

  todo-api-service:
    build: ./backend
    environment:
      - STORAGE=mysql
      - MYSQL_HOST=database
      - MYSQL_USER=ernie
      - MYSQL_PWD=devops
      - MYSQL_DB=examen
    depends_on:
      - database
  
  database:
    image: mysql:8.0.29-debian
    environment:
      MYSQL_DATABASE: 'examen'
      MYSQL_USER: 'ernie'
      MYSQL_PASSWORD: 'devops'
      MYSQL_ROOT_PASSWORD: 'devops'
    volumes:
      - db:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

volumes:
  db:
