version: '3.9'

services:
  front-end:
    image: nginx:1.22
    volumes:
      - ./frontend/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./frontend:/var/www/static/:ro
    ports:
      - 80:80
    depends_on:
      - todo-api-service
    networks:
      - front

  todo-api-service:
    build: ./backend
    environment:
      - STORAGE=mysql
      - MYSQL_HOST=database
      - MYSQL_USER
      - MYSQL_PWD
      - MYSQL_DB
    depends_on:
      - database
    networks:
      - front
      - back  

  database:
    image: mysql:8.0.29-debian
    environment:
      - MYSQL_DATABASE=${MYSQL_DB}
      - MYSQL_USER
      - MYSQL_PASSWORD=${MYSQL_PWD}
      - MYSQL_ROOT_PASSWORD
    volumes:
      - db:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - 3306:3306
    networks:
      - back

volumes:
  db:

networks:
  front:
  back:
