version: '3.9'

services:
  front-end:
    image: nginx:1.22
    volumes:
      - ./frontend/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./frontend:/var/www/static/:ro
    ports:
      - 80:80
    depends_on:
      - todo-api-service

  todo-api-service:
    build: ./backend
    environment:
      - STORAGE=mysql
      - MYSQL_HOST=database
      - MYSQL_USER=ernie
      - MYSQL_PWD=devops
      - MYSQL_DB=examen